name: Build and Release Executables

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Build with PyInstaller
        run: pyinstaller windows.spec
        
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/OptiWise-windows.exe

  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install build essentials (for Linux)
        run: sudo apt-get update && sudo apt-get install -y zip
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Build with PyInstaller
        run: pyinstaller linux.spec
        
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: dist/OptiWise-linux

  create-release:
    name: Create GitHub Release
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Zip files for release
        run: |
          zip -j OptiWise-windows-${{ github.ref_name }}.zip artifacts/windows-build/OptiWise-windows.exe
          zip -j OptiWise-linux-${{ github.ref_name }}.zip artifacts/linux-build/OptiWise-linux

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: Automated release for version ${{ github.ref_name }}.
          files: |
            OptiWise-windows-*.zip
            OptiWise-linux-*.zip